spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB   # Giới hạn file tối đa 100MB
      max-request-size: 100MB  # Giới hạn tổng request tối đa
  application:
    name: datn
  datasource:
    url: jdbc:mysql://localhost:3333/datn_new?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: Asia/Ho_Chi_Minh
  web:
    resources:
      static-locations: file:uploads/
  mail:
    from: buixuanhienmy@gmail.com
    name: Bùi Xuân Hiền
    host: smtp.gmail.com
    port: 587
    username: buixuanhienmy@gmail.com
    password: oikykwowpdyyoqkm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.protocols: TLSv1.2
endpoint:
  confirmUser: http://localhost:${server.port}/api/auth/reset-password
server:
  port: 8071

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
  resetKey: 2OeEeG48CvIcH1K0UAXbSo/7gPj3QLJ7MnQZuscRirQ=

maxFailedLoginAttempts: 5

message:
  queue:
    forgot-password-threads: 2
    forgot-password-max-threads: 5
    retry-max-times: 3


host-ai: http://127.0.0.1:5000
cors:
  allowed-origins: "http://localhost:3000, http://localhost:8080"
